version: '3.7'

services:
  reverseproxy:
    image: nginx
    container_name: nginx
    depends_on:
      - sish
    ports:
      - 443:443
    volumes:
      - ./nginx-preread-protocol.conf:/etc/nginx/nginx.conf:ro
    network_mode: host
  letsencrypt:
    image: adferrand/dnsrobocert:latest
    container_name: letsencrypt-dns
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/etc/letsencrypt
      - ./le-config.yml:/etc/dnsrobocert/config.yml
    restart: always
  sish:
#    image: antoniomika/sish:latest
    image: sish-grr-fix:latest
    container_name: sish
    depends_on: 
      - letsencrypt
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./pubkeys:/pubkeys
      - ./keys:/keys
      - ./ssl:/ssl
      - ./log:/log
    command: |
      --authentication=true
      --authentication-password=YOUR-PASSWORD
      --ssh-address=:2222
      --http-address=:80
      --https-address=:8443
      --https=true
      --https-certificate-directory=/ssl
      --https-ondemand-certificate=false
      --https-ondemand-certificate-accept-terms=true
      --https-ondemand-certificate-email=YOUREMAIL@EMAIL.COM
      --private-key-location=/keys/ssh_key
      --private-key-passphrase=YOUR-PASSPHRASE
      --bind-random-ports=false
      --bind-random-subdomains=true
      --bind-random-subdomains-length=8
      --domain=YOUR.DOMAIN
      --debug=false
      --log-to-file=true
      --log-to-file-path=/log/sish.log
      --redirect-root=true
      --redirect-root-location=https://github.com
    network_mode: host
    restart: always
